// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/countdown.tsx";
import * as $6 from "./routes/generic/[...index].tsx";
import * as $7 from "./routes/github/[username].tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/middleware.tsx";
import * as $10 from "./routes/search.tsx";
import * as $11 from "./routes/user/[username]/profile.tsx";
import * as $$0 from "./islands/Input.tsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/about.tsx": $3,
    "./routes/api/joke.ts": $4,
    "./routes/countdown.tsx": $5,
    "./routes/generic/[...index].tsx": $6,
    "./routes/github/[username].tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/middleware.tsx": $9,
    "./routes/search.tsx": $10,
    "./routes/user/[username]/profile.tsx": $11,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
